# This file configures sops for encrypting/decrypting secrets
# Replace the age key with your actual public key after running:
# age-keygen -o ~/.config/sops/age/keys.txt

keys:
  - &admin age1XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

creation_rules:
  - path_regex: secrets/.*\.(yaml|yml|json|env|sops)$
    key_groups:
      - age:
          - *admin